version: '3'
services:
  web:
    image: php:8.0-apache
    container_name: laravel-web
    build:
        context: ./server
        dockerfile: Dockerfile
    ports :
     - "80:80"
    volumes:
     - ./www:/var/www/html/
     - ./server/000-default.conf:/etc/apache2/sites-available/000-default.conf
     - ./server/apache2.conf:/etc/apache2/apache2.conf
     - ./server/php.ini:/usr/local/etc/php/php.ini
    depends_on:
     - database
    networks: 
     - app_network

  database:
    image: mysql:5.7
    container_name: laravel-db
    ports :
      - "3310:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    networks: 
     - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-laravel
    depends_on:
      - database
    ports:
      - 8891:80
    environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=database

networks: 
  app_network:
    driver: bridge
      